### ISSUE TITLE
[Feature]: Kubectl user can see whether a CFRoute is valid or invalid

### ISSUE THREAD

**Issue by davewalter** [cloudfoundry/cf-k8s-controllers#102]
### Background

**As a** developer using kubectl
**I want** to see whether a CFRoute resource is invalid and, if so, why
**So that** debug routing issues within the platform

### Acceptance Criteria

**GIVEN** that I am targeting a K8s cluster 
**AND** that I have followed the README instructions to install the Controllers
**WHEN** I apply the `cfdomain.yaml` and `cfroute.yaml` resources in config/samples directory
**THEN** I should see all those operations succeed
**AND** I should see that the status section of the output from `kubectl get cfroute 84afc0f2-3dc2-4709-9fc8-8340be584a43 -o yaml` looks like the following

```yaml
status:
  currentStatus: valid
  description: Valid CFRoute
  conditions:
  - type Valid
    status: True
    reason: Valid
    message: Valid CFRoute
    lastTransitionTime: 2021-10-14T12:34:56Z
```

**GIVEN** that I am targeting a K8s cluster 
**AND** that I have followed the README instructions to install the Controllers
**WHEN** I apply just the `cfroute.yaml` resource in config/samples directory
**THEN** I should see the operation succeed
**AND** I should see that the status section of the output from `kubectl get cfroute 84afc0f2-3dc2-4709-9fc8-8340be584a43 -o yaml` looks like the following

```yaml
status:
  currentStatus: invalid
  description: Invalid domain reference
  conditions:
  - type Valid
    status: False
    reason: "InvalidDomainRef"
    message: "Spec.DomainRef.Name unresolved domain reference: \"default/5b5032ab-7fc8-4da5-b853-821fd1879201\" not found"
    lastTransitionTime: 2021-10-14T12:34:56Z
```
**WHEN** I then apply the `cfdomain.yaml` resource in config/samples directory
**THEN** I should see the operation succeed
**AND** I should see that the status section of the output from `kubectl get cfroute 84afc0f2-3dc2-4709-9fc8-8340be584a43 -o yaml` looks like the following

```yaml
status:
  currentStatus: valid
  description: Valid CFRoute
  conditions:
  - type Valid
    status: True
    reason: Valid
    message: Valid CFRoute
    lastTransitionTime: 2021-10-14T12:34:56Z
```

### Dev Notes

* See the [`Status Reporting section of the Contour HTTPProxy Fundamentals`](https://projectcontour.io/docs/main/config/fundamentals/#status-reporting) doc for inspiration.
* We should add invalid status messages for each failure case in the CFRoute reconcile logic.
* Only set an invalid status if the CFRoute reconcile loop returns an error. Don't worry about reflecting the status of the underlying HTTPProxy resources for now.
* We do need to handle the case where the CFDomain is created **after** the CFRoute, which will initially lead to an invalid route that later becomes valid.
