### ISSUE TITLE
[Feature]: Developer can Apply a Minimal Space Manifest to Create Processes and Update Process Attributes (Command and Scaling)

### ISSUE THREAD

**Issue by tcdowney** [cloudfoundry/cf-k8s-controllers#155]
### Blockers/Dependencies

* https://github.com/cloudfoundry/cf-k8s-api/issues/144

### Background

**As an** App Developer
**I want** to be able to provide configuration for my App in the form of a (semi) declarative manifest
**So that** I can configure my App without scripting imperative CLI commands or orchestrating a bunch of API endpoint calls

Users can provide their own manifest along with their App Source code (or in a different directory via the `--manifest` and `-f` flags) and modern CF CLIs will interpret `cf push` flags and apply those on top of it. Even if the user doesn't provide a manifest, the CLI will construct one and use it for the bulk of the app creation/configuration flow of `cf push`.

There are many attributes that can be supported in an App Manifest:
* https://v3-apidocs.cloudfoundry.org/version/3.108.0/index.html#the-manifest-schema
* https://docs.cloudfoundry.org/devguide/deploy-apps/manifest-attributes.html

For the sake of this story, we aim to support a subset, the ability to create and update Processes:
```yaml
---
version: 1
applications:
  - name: app1
    processes:
      - type: web
        command: start-web.sh
        disk_quota: 512M
        instances: 3
        memory: 500M
      - type: worker
        command: start-worker.sh
        disk_quota: 1G
        instances: 2
        memory: 256M
```

The manifest supports "friendly" options for `disk_quota` and `memory` and converts them to the MB integer values that users expect. We can use https://github.com/cloudfoundry/bytefmt to do this parsing.

**Note:** Existing Processes that are not specified by the manifest are left alone.

### Happy Path (App does not exist)

**GIVEN** I have a manifest that specifies an App that does not currently exist
**WHEN I** send it to the CF API Shim via the following request
```
curl "https://api-shim.example.org/v3/spaces/<space-guid>/actions/apply_manifest" \
  -X POST \
  -H "Authorization: bearer [token]" \
  -H "Content-type: application/x-yaml" \
  --data-binary @/path/to/manifest.yml
```

where the file `@/path/to/manifest.yml` looks like
```yaml
---
version: 1
applications:
  - name: app1
    processes:
      - type: web
        command: start-web.sh
        disk_quota: 512M
        instances: 3
        memory: 500M
      - type: worker
        command: start-worker.sh
        disk_quota: 1G
        instances: 2
        memory: 256M
```

**THEN** I see a `CFApp` created in the appropriate namespace in the `STOPPED` state and `CFProcesses` with config that matches what we specified. The response from the API should have no body, but return the following

```
HTTP/1.1 202 Accepted
Location: https://api-shim.example.org/v3/jobs/sync-space.apply_manifest-<space-guid>
```

---

### Happy Path (App does exist and is `STARTED`)

**GIVEN** I have an existing App and it is in the `STARTED` state (state doesn't actually matter too much, it shouldn't be changed)
**WHEN I** send it to the CF API Shim via the following request
```
curl "https://api-shim.example.org/v3/spaces/<space-guid>/actions/apply_manifest" \
  -X POST \
  -H "Authorization: bearer [token]" \
  -H "Content-type: application/x-yaml" \
  --data-binary @/path/to/manifest.yml
```

where the file `@/path/to/manifest.yml` looks like
```yaml
---
version: 1
applications:
  - name: app1
    processes:
      - type: web
        command: start-web.sh
        disk_quota: 512M
        instances: 3
        memory: 500M
      - type: worker
        command: start-worker.sh
        disk_quota: 1G
        instances: 2
        memory: 256M
```

**THEN** I see the existing `CFApp` configured and remain in the `STARTED` state. Any existing `CFProcesses` should be updated with config that matches what we specified. Any existing `CFProcesses` that are not present in the manifest should be left alone. Any missing `CFProcesses` should be created. The response from the API should have no body, but return the following

```
HTTP/1.1 202 Accepted
Location: https://api-shim.example.org/v3/jobs/sync-space.apply_manifest-<space-guid>
```

---

### Happy Path (Legacy Manifest without Processes array)

**GIVEN** I have an existing App
**WHEN I** send it to the CF API Shim via the following request
```
curl "https://api-shim.example.org/v3/spaces/<space-guid>/actions/apply_manifest" \
  -X POST \
  -H "Authorization: bearer [token]" \
  -H "Content-type: application/x-yaml" \
  --data-binary @/path/to/manifest.yml
```

where the file `@/path/to/manifest.yml` looks like
```yaml
---
version: 1
applications:
  - name: app1
    command: start-web.sh
    disk_quota: 512M
    instances: 3
    memory: 500M
```

**THEN** I see the existing `CFApp` configured. If it exists, the `web` type `CFProcess` should be updated with the `command`, `disk_quota`, `instances`, and `memory` values. If the `web` process does not exist, it should be created.

```
HTTP/1.1 202 Accepted
Location: https://api-shim.example.org/v3/jobs/sync-space.apply_manifest-<space-guid>
```

---

### Manifest Contains Config We Don't Support

**GIVEN** I provide a manifest with attributes that our API Shim does not currently support
**WHEN I** send it to the CF API Shim via the following request
```
curl "https://api-shim.example.org/v3/spaces/<space-guid>/actions/apply_manifest" \
  -X POST \
  -H "Authorization: bearer [token]" \
  -H "Content-type: application/x-yaml" \
  --data-binary @/path/to/manifest.yml
```

where the file `@/path/to/manifest.yml` looks like
```yaml
version: 1
applications:
- name: app1
  buildpacks:
  - ruby_buildpack
  - java_buildpack
  env:
    VAR1: value1
    VAR2: value2
  routes:
  - route: route.example.com
  - route: another-route.example.com
    protocol: http2
  services:
  - my-service1
  - my-service2
  - name: my-service-with-arbitrary-params
    binding_name: my-binding
    parameters:
      key1: value1
      key2: value2
  stack: cflinuxfs3
  metadata:
    annotations:
      contact: "bob@example.com jane@example.com"
    labels:
      sensitive: true
  processes:
  - type: web
    command: start-web.sh
    disk_quota: 512M
    health-check-http-endpoint: /healthcheck
    health-check-type: http
    health-check-invocation-timeout: 10
    instances: 3
    memory: 500M
    timeout: 10
  - type: worker
    command: start-worker.sh
    disk_quota: 1G
    health-check-type: process
    instances: 2
    memory: 256M
    timeout: 15
```

**THEN I** I see the `CFApp` and `CFProcesses` updated for the fields we *do support*. All other fields are ignored, but the request should succeed.

```
HTTP/1.1 202 Accepted
Location: https://api-shim.example.org/v3/jobs/sync-space.apply_manifest-<space-guid>
```

---

### Manifest Contains Invalid Config that We Do Support

**GIVEN** I provide a manifest with attributes that our API Shim supports, but with invalid data
**WHEN I** send it to the CF API Shim via the following request
```
curl "https://api-shim.example.org/v3/spaces/<space-guid>/actions/apply_manifest" \
  -X POST \
  -H "Authorization: bearer [token]" \
  -H "Content-type: application/x-yaml" \
  --data-binary @/path/to/manifest.yml
```

```yaml
---
version: 1
applications:
  - name: app1
    processes:
      - type: web
        command: start-web.sh
        disk_quota: foo
        instances: -3
        memory: 500M
      - type: worker
        command: start-worker.sh
        disk_quota: -1G
        instances: seven
        memory: bar
```

**THEN I** receive a `422` with the following error message*

```json
HTTP/1.1 422 Unprocessable Entity
Content-Type: application/json

{
   "errors": [
      {
         "detail": "Manifest contains invalid attributes",
         "title": "CF-UnprocessableEntity",
         "code": 10008
      }
   ]
}
```

### Dev Notes

* We want the manifest to function the same as the individual endpoints for various actions it can take. Try and factor out logic into reusable pieces where possible. The main difference here should be in the request parsing layer.
* Refer to the CCNG Space Manifest controller (and its message/action classes) for inspiration: https://github.com/cloudfoundry/cloud_controller_ng/blob/main/app/controllers/v3/space_manifests_controller.rb
  * Look at Cloud Controller [AppApplyManifestimplementation](https://github.com/cloudfoundry/cloud_controller_ng/blob/main/app/actions/app_apply_manifest.rb)
* Fields we don't support should just be ignored.
* This is the library Cloud Controller uses to parse the "human readable" `disk_quota` and `memory` values: https://github.com/goodmustache/palm_civet/blob/master/lib/palm_civet.rb. We can use https://github.com/cloudfoundry/bytefmt to do this in our codebase
* Discussion around Process start command precedence
  * This is really complicated.. Cloud Controller currently has logic around when to use buildpack/Procfile specified command vs user Specified
  *  https://github.com/cloudfoundry/cloud_controller_ng/blob/20150b672db70d940e0d3136d3acae371eb4c18e/app/models/runtime/process_model.rb#L400-L405
  * For this story we've said start command precedence is out of scope and the behavior is not currently specified. We can do that in a future story if desired
* Processes should be created similar to how the AppController does [here](https://github.com/cloudfoundry/cf-k8s-controllers/blob/32f8a1c7d2f2270c6686b457528c649b86bc1f72/controllers/workloads/cfapp_controller.go#L128). This controller currently sets default values for certain fields. We want to make sure these defaults are set in a consistent way no matter how the Process is made (`kubectl`, manifest endpoint, `AppController`) so consider how we should do that and write a separate story to do it.
