### ISSUE TITLE
[Feature]: App Developer can Apply a Minimal Space Manifest to Create New Apps

### ISSUE THREAD

**Issue by tcdowney** [cloudfoundry/cf-k8s-controllers#165]
### Background

**As an** App Developer
**I want** to be able to provide configuration for my App in the form of a (semi) declarative manifest
**So that** I can configure my App without scripting imperative CLI commands or orchestrating a bunch of API endpoint calls

Users can provide their own manifest along with their App Source code (or in a different directory via the `--manifest` and `-f` flags) and modern CF CLIs will interpret `cf push` flags and apply those on top of it. Even if the user doesn't provide a manifest, the CLI will construct one and use it for the bulk of the app creation/configuration flow of `cf push`.

There are many attributes that can be supported in an App Manifest:
* https://v3-apidocs.cloudfoundry.org/version/3.108.0/index.html#the-manifest-schema
* https://docs.cloudfoundry.org/devguide/deploy-apps/manifest-attributes.html

For the sake of this story, we aim to support the bare minimum that a manifest might contain, an application name.
```yaml
---
version: 1
applications:
  - name: app1
```

---

### Happy Path (App does not exist)

**GIVEN** I have a manifest that specifies an App that does not currently exist
**WHEN I** send it to the CF API Shim via the following request
```
curl "https://api-shim.example.org/v3/spaces/<space-guid>/actions/apply_manifest" \
  -X POST \
  -H "Authorization: bearer [token]" \
  -H "Content-type: application/x-yaml" \
  --data-binary @/path/to/manifest.yml
```

where the file `@/path/to/manifest.yml` looks like
```yaml
---
version: 1
applications:
  - name: app1
```

**THEN** I see a `CFApp` named `app1` created in the appropriate namespace in the `STOPPED` state.

```
HTTP/1.1 202 Accepted
Location: https://api-shim.example.org/v3/jobs/sync-space.apply_manifest-<space-guid>
```

---

### Happy Path (App DOES exist)

**GIVEN** I have a manifest that specifies an App that does currently exist
**WHEN I** send it to the CF API Shim via the following request
```
curl "https://api-shim.example.org/v3/spaces/<space-guid>/actions/apply_manifest" \
  -X POST \
  -H "Authorization: bearer [token]" \
  -H "Content-type: application/x-yaml" \
  --data-binary @/path/to/manifest.yml
```

where the file `@/path/to/manifest.yml` looks like
```yaml
---
version: 1
applications:
  - name: app1
```

**THEN** I see that the `CFApp` named `app1` is unchanged.

```
HTTP/1.1 202 Accepted
Location: https://api-shim.example.org/v3/jobs/sync-space.apply_manifest-<space-guid>
```

---

### Manifest Contains Multiple Apps

**GIVEN** I have a manifest that contains multiple apps
**WHEN I** send it to the CF API Shim via the following request
```
curl "https://api-shim.example.org/v3/spaces/<space-guid>/actions/apply_manifest" \
  -X POST \
  -H "Authorization: bearer [token]" \
  -H "Content-type: application/x-yaml" \
  --data-binary @/path/to/manifest.yml
```

where the file `@/path/to/manifest.yml` looks like
```yaml
---
version: 1
applications:
  - name: app1
  - name: app2
```

**THEN I** receive a `422` with the following error message

```json
HTTP/1.1 422 Unprocessable Entity
Content-Type: application/json

{
   "errors": [
      {
         "detail": "Manifests that specify multiple apps are not currently supported",
         "title": "CF-UnprocessableEntity",
         "code": 10008
      }
   ]
}
```

---

### Manifest Contains Config We Don't Support

**GIVEN** I provide a manifest with attributes that our API Shim does not currently support
**WHEN I** send it to the CF API Shim via the following request
```
curl "https://api-shim.example.org/v3/spaces/<space-guid>/actions/apply_manifest" \
  -X POST \
  -H "Authorization: bearer [token]" \
  -H "Content-type: application/x-yaml" \
  --data-binary @/path/to/manifest.yml
```

where the file `@/path/to/manifest.yml` looks like
```yaml
version: 1
applications:
- name: app1
  buildpacks:
  - ruby_buildpack
  - java_buildpack
  env:
    VAR1: value1
    VAR2: value2
  routes:
  - route: route.example.com
  - route: another-route.example.com
    protocol: http2
  services:
  - my-service1
  - my-service2
  - name: my-service-with-arbitrary-params
    binding_name: my-binding
    parameters:
      key1: value1
      key2: value2
  stack: cflinuxfs3
  metadata:
    annotations:
      contact: "bob@example.com jane@example.com"
    labels:
      sensitive: true
  processes:
  - type: web
    command: start-web.sh
    disk_quota: 512M
    health-check-http-endpoint: /healthcheck
    health-check-type: http
    health-check-invocation-timeout: 10
    instances: 3
    memory: 500M
    timeout: 10
  - type: worker
    command: start-worker.sh
    disk_quota: 1G
    health-check-type: process
    instances: 2
    memory: 256M
    timeout: 15
```

**THEN I** see the `CFApp` and `CFProcesses` updated for the fields we *do support*. All other fields are ignored, but the request should succeed.

Response should look like:

```
HTTP/1.1 202 Accepted
Location: https://api-shim.example.org/v3/jobs/sync-space.apply_manifest-<space-guid>
```

### Dev Notes
* The `version` attribute is used by Cloud Controller to help it support additional manifest schemas in the future. We can ignore it for now.
* We want the manifest to function the same as the individual endpoints for various actions it can take. Try and factor out logic into reusable pieces where possible and it makes sense to do so. The main difference here should be in the request parsing layer.
* Refer to the CCNG Space Manifest controller (and its message/action classes) for inspiration: https://github.com/cloudfoundry/cloud_controller_ng/blob/main/app/controllers/v3/space_manifests_controller.rb
  * Look at Cloud Controller [AppApplyManifest implementation](https://github.com/cloudfoundry/cloud_controller_ng/blob/main/app/actions/app_apply_manifest.rb) as well
* Only support the App Manifest including a single App for now
* Fields we don't support should just be ignored.
* Make sure our YAML parser is not susceptible to https://github.com/kubernetes/kubernetes/issues/83253
* Env Variables are "merged" with the original set, not specified are left alone, specified are overwritten
* You will need to implement two new actions for update secret and update processType and command
* For the most part manifest applications don't delete anything.
