### ISSUE TITLE
[Feature]: Developer can apply a minimal space manifest to map a single route to an app

### ISSUE THREAD

**Issue by acosta11** [cloudfoundry/cf-k8s-controllers#354]
### Background

**As an** App Developer
**I want** to be able to provide route configuration for my App as a declarative manifest
**So that** I can configure routes to my App without scripting imperative CLI commands or orchestrating API calls

For this story, we focus on the creation of explicitly defined routes in the `routes` field of the manifest spec.

```
---
version: 1
applications:
  - name: my-app
     ...
     routes:
     - route: my-app-host.example.com
```

### Acceptance Criteria

**Scenarios**

## Happy Path (Route does not exist)
**GIVEN** I have a cluster with a cfdomain already created for "example.com" and a manifest that specifies a route that does not currently exist
**WHEN I** send it to the CF API Shim with the following request
```
curl "https://api-shim.example.org/v3/spaces/<space-guid>/actions/apply_manifest" \
  -X POST \
  -H "Authorization: bearer [token]" \
  -H "Content-type: application/x-yaml" \
  --data-binary @/path/to/manifest.yml
```
where the filepath refers to a file of the form:
```
---
version: 1
applications:
  - name: app1
    routes:
      - route: my-host.example.com
```
**THEN I** I see a CFRoute created in the appropriate namespace with the specified FQDN mapped to `app1`.
```
HTTP/1.1 202 Accepted
Location: https://api-shim.example.org/v3/jobs/sync-space.apply_manifest-<space-guid>
```

## Happy Path (Route exists but is not mapped to app)
**GIVEN** I have a cluster with a cfdomain already created for "example.com" and a manifest that specifies a route that already exists
**WHEN I** send it to the CF API Shim with the following request
```
curl "https://api-shim.example.org/v3/spaces/<space-guid>/actions/apply_manifest" \
  -X POST \
  -H "Authorization: bearer [token]" \
  -H "Content-type: application/x-yaml" \
  --data-binary @/path/to/manifest.yml
```
where the filepath refers to a file of the form:
```
---
version: 1
applications:
  - name: app1
    routes:
      - route: my-host.example.com
```
**THEN I** I see the CFRoute with the specified FQDN updated to be mapped to `app1`.
```
HTTP/1.1 202 Accepted
Location: https://api-shim.example.org/v3/jobs/sync-space.apply_manifest-<space-guid>
```

## Happy Path (newly created Route includes a path)
**GIVEN** I have a cluster with a cfdomain already created for "example.com" and a manifest that specifies a route that does not currently exist
**WHEN I** send it to the CF API Shim with the following request
```
curl "https://api-shim.example.org/v3/spaces/<space-guid>/actions/apply_manifest" \
  -X POST \
  -H "Authorization: bearer [token]" \
  -H "Content-type: application/x-yaml" \
  --data-binary @/path/to/manifest.yml
```
where the filepath refers to a file of the form:
```
---
version: 1
applications:
  - name: app1
    routes:
      - route: my-host.example.com/some-path
```
**THEN I** I see a CFRoute created in the appropriate namespace with the specified FQDN **and path** mapped to `app1`.
```
HTTP/1.1 202 Accepted
Location: https://api-shim.example.org/v3/jobs/sync-space.apply_manifest-<space-guid>
```

### Unhappy Path
**GIVEN** I have a cluster and a manifest that specifies an invalid route (E.G. domain not yet created)
**WHEN I** send it to the CF API Shim with the following request
```
curl "https://api-shim.example.org/v3/spaces/<space-guid>/actions/apply_manifest" \
  -X POST \
  -H "Authorization: bearer [token]" \
  -H "Content-type: application/x-yaml" \
  --data-binary @/path/to/manifest.yml
```
where the filepath refers to a file of the form:
```
---
version: 1
applications:
  - name: app1
    routes:
      - route: my-host.example.com
```
**THEN I** I see the CFRoute with the specified FQDN is **NOT** created.
```
HTTP/1.1 422 Unprocessable Entity
Content-Type: application/json

{
   "errors": [
      {
         "detail": "Manifest contains invalid attributes",
         "title": "CF-UnprocessableEntity",
         "code": 10008
      }
   ]
}
```

### Dev Notes

* We want the manifest to function the same as the individual endpoints for various actions it can take. Try and factor out logic into reusable pieces where possible. The main difference here should be in the request parsing layer.
* Much of the logic for route manifest apply is in https://github.com/cloudfoundry/cloud_controller_ng/blob/a63cfe80d92e8f153db89d10963f10f9173a2f69/app/actions/app_apply_manifest.rb#L88-L121
* Only support the first route in the routes field for now and ignore related unsupported fields. We will follow up with further field support in separate issues.
* Only support HTTP routing initially (so port may not be specified on the route)
