### ISSUE TITLE
[Explore]: Spike out User Provided Service Instances Support Using Kubernetes Service Bindings for Runtime

### ISSUE THREAD

**Issue by tcdowney** [cloudfoundry/cf-k8s-controllers#367]
### Background

Developers using CF can bind their apps to two types of services: user provided and managed. Managed Services on CF are those whose lifecycle and credentials are controlled by a separate service broker. Cloud Foundry interfaces with these brokers via the Open Service Broker API and exposes them to developers through its Service Marketplace. Developers can ask brokers to create new Service Instances for them and then bind their apps (via a Service Binding) to these instances. As part of that binding, the broker will supply credentials and other important information (such as connection strings, certs, port numbers, etc.)  to the app via the `VCAP_SERVICES` environment variable.

**User Provided Services** are managed directly by CF users. Users can create what are known as “User Provided Service Instances” (UPSIs) with an arbitrary set of configuration. When a Service Binding is created to one of these UPSIs, the configuration is shared with the bound app under the same `VCAP_SERVICES` environment variable. For example, a developer may be given credentials to an already existing database instance and use a UPSI to expose it to their app running on TAS.

As a MVP, we are looking to support basic (just credentials -- no route services, no syslog drains) User Provided Service Instances first before moving on to exploring the more complicated world of managed services.

There are existing projects in the Kubernetes ecosystem such as the [Kubernetes Service Bindings Specification](https://github.com/servicebinding/spec) that provide custom resources and "duck types" (`ProvisionedService`) that we believe we can leverage to achieve our immediate compatibility goals while providing flexibility for the evolving services landscape in the Kubernetes community.

---

### Acceptance Criteria

We want to explore how we might implement support for User Provided Service Instances in CF on K8s. 

As part of this exploration let's spike out an implementation using a new `CFServiceInstance` CR that implements the `ProvisionedService` duck type from the K8s Service Binding Spec as well as the `ServiceBinding` custom resource.

### Example `CFServiceInstance`
```yaml
---
kind: CFServiceInstance
…
metadata:
  …
  name: my-upsi
  namespace: my-cf-space-guid
spec:
  …
  type: user-provided
…
status:
  …
  binding:
    name: my-upsi-credentials
```

At a minimum we want credentials from multiple bindings to be aggregated under a `VCAP_SERVICES` env var so that existing CF apps can continue to work. This looks something like this in a CF for VMs app runtime and staging containers:

```console
vcap@ea6b07a8-bb91-4b16-43d3-9b4e:~$ env | grep VCAP_SERVICES -A 18
VCAP_SERVICES={"user-provided":[{
  "label": "user-provided",
  "name": "test-upsi",
  "tags": [

  ],
  "instance_guid": "f4a3a20f-8fd5-4233-afd3-cfcd863986e1",
  "instance_name": "test-upsi",
  "binding_guid": "13bbc5ee-14a5-400b-a354-a68dd52a1807",
  "binding_name": null,
  "credentials": {
    "user-provided-key-1": "user-provided-value-1",
    "user-provided-key-2": "user-provided-value-2"
  },
  "syslog_drain_url": null,
  "volume_mounts": [

  ]
}]}
```

We should also explore what it looks like to actually implement the Kubernetes Service Bindings spec and project these credentials as volumes on the app container. See the [Workload Projection](https://github.com/servicebinding/spec#workload-projection) portion of the specification for more details on what that looks like.

## Questions to answer

* What are some ways to project credentials from the service binding into the app runtime container?
  * In our `CFProcess` reconciler?
  * Mutating webhook on `Pods`?
  * Something else?
* How do we aggregate multiple credentials under `VCAP_SERVICES`? How do we make them volume mounts?
* What is missing from the example CR that's necessary for this to work and power the V3 Services APIs? We ultimately want to support the full set of CLI commands here, such as: `cf create-user-provided-service`, `cf bind-service`, `cf services`, `cf update-user-provided-service`, `cf unbind-service`, etc.
  * Read through, understand, and explore how these APIs behave on CF for VMs: https://v3-apidocs.cloudfoundry.org/version/3.112.0/index.html#service-instances 

TODO write a separate story for staging:
* What are some ways to project credentials from the service binding into the app staging container?
  * In our `CFBuild` reconciler?
  * Mutating webhook on `Pods`? 
  * Is there a point of projecting them as `VCAP_SERVICES` for staging or do CNBs not even look at that.

### Output
A proposal to share with the CF on K8s SIG group about how we're going to tackle this.

### Number of days this exploration is expected to take. This is what is “pointed”.

3

### Dev Notes

---

## Resources:

* [CF Services Overview docs](https://docs.cloudfoundry.org/services/overview.html)
* [CF User-Provided Service Instance docs](https://docs.cloudfoundry.org/devguide/services/user-provided.html)
* [Kubernetes Service Bindings Spec](https://github.com/servicebinding/spec)

**Comment by akrishna90** [comment]
@julian-hj and I investigated the Kubernetes service binding spec using a concrete implementation here - https://github.com/vmware-labs/service-bindings. 

We were able to bind a service to an app (pushed using `cf push`) by using the service-binding and secret below. We verified the service-binding by ssh-ing into the app and listing the volume mounts. This implementation of service binding spec doesn't solve the problem of exposing the service credentials as a VCAP_SERVICES env variable. 

### Secret

```
apiVersion: v1
kind: Secret
metadata:
  name: node-db
type: servicebinding.io/mysql
stringData:
  type: mysql
  provider: mariadb
  host: node-db
  port: "3306"
  database: default
  # demo credentials
  username: user
  password: pass

```

### Service Binding
```
---
apiVersion: servicebinding.io/v1alpha3
kind: ServiceBinding
metadata:
  name: node-db
spec:
  # direct Secret reference is used for compatibility, but not recommended for dynamically provisioned services
  service:
    apiVersion: v1
    kind: Secret
    name: node-db
  workload:
    apiVersion: apps/v1
    kind: Statefulset
    name: cfeecdaf-47e4-44a0-8b53-ce3b391b7530-bef260a699
```
