### ISSUE TITLE
[Feature]: Merge CF Build and CF Droplet CRs

### ISSUE THREAD

**Issue by gnovv** [cloudfoundry/cf-k8s-controllers#52]
### Background

After the explore to merge [CF Build and Droplet](https://github.com/cloudfoundry/cf-crd-explorations/issues/76), we created a [proposal CR](https://docs.google.com/document/d/1p5TaFM93Zmqd0kxIkjHciA_MhttMUTefhqc3fzF6qzs/view#heading=h.a8pae1sdrk1n) and [spike implementation](https://github.com/cloudfoundry/cf-crd-explorations/tree/issue-76).

Please modify the CF Build CR to match the spec from the proposal, and delete the CF Droplet, then clean up any orphaned files.

Additionally, please update the sample CRs.

Example CR:

```
---
# Defines a build for the provided package. Triggers the staging process which results in a runnable container image.
# Successful CF Builds automatically receive CF Droplets.
apiVersion: apps.cloudfoundry.org/v1alpha1
kind: CFBuild
metadata:
  # apps.cloudfoundry.org/ labels are all managed by a mutating webhook
  labels:
    apps.cloudfoundry.org/appGuid: 14dcda7d-1fa1-4a91-b437-fbdba20e8c5a
    apps.cloudfoundry.org/packageGuid: ac85ad52-f52f-48e3-8c99-5e7badbe79c5
  name: 1591ee05-e208-4cf3-a662-1c2da42f20a7
  namespace: default
  # ownerReferences are managed by mutating webhook that looks at appRef
  ownerReferences:
    - apiVersion: apps.cloudfoundry.org/v1alpha1
      kind: CFApp
      name: 14dcda7d-1fa1-4a91-b437-fbdba20e8c5a
      uid: 2c5e9145-dee1-407f-b507-4ea84b25a7b4
spec:
  appRef:
    name: 14dcda7d-1fa1-4a91-b437-fbdba20e8c5a
  packageRef:
    name: ac85ad52-f52f-48e3-8c99-5e7badbe79c5
  stagingMemoryMB: 1024
  stagingDiskMB: 1024 # <----------- can we even do this?
  lifecycle:
    type: buildpack
    data:
      buildpacks: []
      stack: cflinuxfs3
status:
  conditions:
    - type: Succeeded
      status: "True"
      reason: Buildpack
      message: ""
    - type: Staging
      status: "False"
      reason: Succeeded
      message: ""
    - type: BuildReady
      status: "True"
      reason: Buildpack
      message: ""
    - type: DropletReady
      status: "True"
      reason: Buildpack
      message: ""
  droplet:
    ports: [80, 443] # spec.ports is the set of ports exposed on the Processes of the Droplet
    processTypes:
      - type: web
        command: bundle exec rackup config.ru -p $PORT -o 0.0.0.0
      - type: worker
        command: bundle exec rackup config.ru
    registry:
      image: gcr.io/cf-relint-greengrass/cf-crd-staging-spike/buildpack/14dcda7d-1fa1-4a91-b437-fbdba20e8c5a@sha256:17ef1315d87bb57657ee14f387394f56d6f4429151262d731a31e92e5497ad35
      imagePullSecrets:
      - name: app-registry-credentials
```

### Action to take

Delete CF Droplet CR
Modify CF Build CR to align with [proposal](https://docs.google.com/document/d/1p5TaFM93Zmqd0kxIkjHciA_MhttMUTefhqc3fzF6qzs)
Clean up & regenerate files
Add new example build CR to config/samples

### Impact

We haven't implemented the controllers / endpoints for the Build/Droplet CR so there should be minimal changes required to the API shim and controllers.

### Dev Notes

- No tests should be required to make this change
- Please ensure that the sample CR is apply-able with the new CF Build CRD
- Leave the references on other CRs the same -- they can still say `dropletRef`. Eventually if we find there are other consumers of those CRs we can consider adding additional fields like `kind` and `apiVersion` if we want.
- Memory and disk limits are present on CF Builds -- we are adding them last minute here. Think about how they're formatted and if disk makes sense in this context. We use them in https://github.com/cloudfoundry/cf-k8s-api/issues/53
