### ISSUE TITLE
[Feature]: API Client can list service bindings via `GET /v3/service_credential_bindings`

### ISSUE THREAD

**Issue by tcdowney** [cloudfoundry/cf-k8s-controllers#603]
### Blockers/Dependencies

* Not a strict blocker, but this story may be easier once the `POST /v3/service_credential_bindings` story is completed. https://github.com/cloudfoundry/cf-k8s-controllers/issues/458

### Background

**As a** client of the API Shim
**I want** to be able to list service bindings
**So that** I can discover which service instances are bound to which apps

The CF CLI makes the following request as part of `cf services`:
```
GET /v3/service_credential_bindings?include=app&service_instance_guids=0c024675-7e0b-475c-8332-74986b5001a2%2C896fd3fa-28ec-42ff-b846-531e2ecabdaa
```

**Note:** Supporting `include=app` will be done as part of https://github.com/cloudfoundry/cf-k8s-controllers/issues/627

### Acceptance Criteria

The following set up applies to all of these scenarios.

1. Created a new Org and Space
2. `cf push app-a` (app guid is `114edd6d-1960-46df-a1dc-0309ce8ed63b`)
3. `cf push app-b` (app guid is `fa1069fb-922a-4a19-8a31-9129a82baff1`)
4. `cf cups service-a` (service instance guid is `5be373e9-309c-4ad9-a705-290525f36bd3`)
5. `cf cups service-b` (service instance guid is `fa0e32b3-e58b-4533-8d61-59ac38b1fa51`)
6. `cf bind-service app-a service-a` (binding guid is `08f1db1a-c7b9-4de2-9afa-5a7e53075d6d`)
7. `cf bind-service app-a service-b` (binding guid is `78a190a3-e3dd-4d42-8158-89aabfbd1673`)
8. `cf bind-service app-b service-b` (binding guid is `9c4cb7fc-eb61-49d8-9c16-a949eae55ed9`)

---

### No Filters

**GIVEN** I have created the apps, UPSIs, and bindings defined above
**WHEN I** make the following request

```
cf curl /v3/service_credential_bindings
```

**THEN I** get back a `200` response that looks similar to the following

```json
{
  "pagination": {
    "total_results": 3,
    "total_pages": 1,
    "first": {
      "href": "https://api.atom-kitten.capi.land/v3/service_credential_bindings?page=1&per_page=50"
    },
    "last": {
      "href": "https://api.atom-kitten.capi.land/v3/service_credential_bindings?page=1&per_page=50"
    },
    "next": null,
    "previous": null
  },
  "resources": [
    {
      "guid": "08f1db1a-c7b9-4de2-9afa-5a7e53075d6d",
      "created_at": "2022-01-31T22:12:01Z",
      "updated_at": "2022-01-31T22:12:01Z",
      "name": null,
      "type": "app",
      "last_operation": {
        "state": "succeeded",
        "description": null,
        "type": "create",
        "updated_at": "2022-01-31T22:12:01Z",
        "created_at": "2022-01-31T22:12:01Z"
      },
      "metadata": {
        "labels": {

        },
        "annotations": {

        }
      },
      "relationships": {
        "service_instance": {
          "data": {
            "guid": "5be373e9-309c-4ad9-a705-290525f36bd3"
          }
        },
        "app": {
          "data": {
            "guid": "114edd6d-1960-46df-a1dc-0309ce8ed63b"
          }
        }
      },
      "links": {
        "self": {
          "href": "https://api.atom-kitten.capi.land/v3/service_credential_bindings/08f1db1a-c7b9-4de2-9afa-5a7e53075d6d"
        },
        "details": {
          "href": "https://api.atom-kitten.capi.land/v3/service_credential_bindings/08f1db1a-c7b9-4de2-9afa-5a7e53075d6d/details"
        },
        "service_instance": {
          "href": "https://api.atom-kitten.capi.land/v3/service_instances/5be373e9-309c-4ad9-a705-290525f36bd3"
        },
        "app": {
          "href": "https://api.atom-kitten.capi.land/v3/apps/114edd6d-1960-46df-a1dc-0309ce8ed63b"
        }
      }
    },
    {
      "guid": "78a190a3-e3dd-4d42-8158-89aabfbd1673",
      "created_at": "2022-01-31T22:12:04Z",
      "updated_at": "2022-01-31T22:12:04Z",
      "name": null,
      "type": "app",
      "last_operation": {
        "state": "succeeded",
        "description": null,
        "type": "create",
        "updated_at": "2022-01-31T22:12:04Z",
        "created_at": "2022-01-31T22:12:04Z"
      },
      "metadata": {
        "labels": {

        },
        "annotations": {

        }
      },
      "relationships": {
        "service_instance": {
          "data": {
            "guid": "fa0e32b3-e58b-4533-8d61-59ac38b1fa51"
          }
        },
        "app": {
          "data": {
            "guid": "114edd6d-1960-46df-a1dc-0309ce8ed63b"
          }
        }
      },
      "links": {
        "self": {
          "href": "https://api.atom-kitten.capi.land/v3/service_credential_bindings/78a190a3-e3dd-4d42-8158-89aabfbd1673"
        },
        "details": {
          "href": "https://api.atom-kitten.capi.land/v3/service_credential_bindings/78a190a3-e3dd-4d42-8158-89aabfbd1673/details"
        },
        "service_instance": {
          "href": "https://api.atom-kitten.capi.land/v3/service_instances/fa0e32b3-e58b-4533-8d61-59ac38b1fa51"
        },
        "app": {
          "href": "https://api.atom-kitten.capi.land/v3/apps/114edd6d-1960-46df-a1dc-0309ce8ed63b"
        }
      }
    },
    {
      "guid": "9c4cb7fc-eb61-49d8-9c16-a949eae55ed9",
      "created_at": "2022-01-31T22:12:07Z",
      "updated_at": "2022-01-31T22:12:07Z",
      "name": null,
      "type": "app",
      "last_operation": {
        "state": "succeeded",
        "description": null,
        "type": "create",
        "updated_at": "2022-01-31T22:12:07Z",
        "created_at": "2022-01-31T22:12:07Z"
      },
      "metadata": {
        "labels": {

        },
        "annotations": {

        }
      },
      "relationships": {
        "service_instance": {
          "data": {
            "guid": "fa0e32b3-e58b-4533-8d61-59ac38b1fa51"
          }
        },
        "app": {
          "data": {
            "guid": "fa1069fb-922a-4a19-8a31-9129a82baff1"
          }
        }
      },
      "links": {
        "self": {
          "href": "https://api.atom-kitten.capi.land/v3/service_credential_bindings/9c4cb7fc-eb61-49d8-9c16-a949eae55ed9"
        },
        "details": {
          "href": "https://api.atom-kitten.capi.land/v3/service_credential_bindings/9c4cb7fc-eb61-49d8-9c16-a949eae55ed9/details"
        },
        "service_instance": {
          "href": "https://api.atom-kitten.capi.land/v3/service_instances/fa0e32b3-e58b-4533-8d61-59ac38b1fa51"
        },
        "app": {
          "href": "https://api.atom-kitten.capi.land/v3/apps/fa1069fb-922a-4a19-8a31-9129a82baff1"
        }
      }
    }
  ]
}
```

---

### Filtering by `service_instance_guids`

**GIVEN** I have created the apps, UPSIs, and bindings defined above
**WHEN I** make the following request to filter by service-b

```
cf curl /v3/service_credential_bindings?service_instance_guids=fa0e32b3-e58b-4533-8d61-59ac38b1fa51
```

**THEN I** get back a `200` response that looks similar to the following (contains the app-a-service-b and app-b-service-b bindings)

```json
{
  "pagination": {
    "total_results": 2,
    "total_pages": 1,
    "first": {
      "href": "https://api.atom-kitten.capi.land/v3/service_credential_bindings?page=1&per_page=50&service_instance_guids=fa0e32b3-e58b-4533-8d61-59ac38b1fa51"
    },
    "last": {
      "href": "https://api.atom-kitten.capi.land/v3/service_credential_bindings?page=1&per_page=50&service_instance_guids=fa0e32b3-e58b-4533-8d61-59ac38b1fa51"
    },
    "next": null,
    "previous": null
  },
  "resources": [
    {
      "guid": "78a190a3-e3dd-4d42-8158-89aabfbd1673",
      "created_at": "2022-01-31T22:12:04Z",
      "updated_at": "2022-01-31T22:12:04Z",
      "name": null,
      "type": "app",
      "last_operation": {
        "state": "succeeded",
        "description": null,
        "type": "create",
        "updated_at": "2022-01-31T22:12:04Z",
        "created_at": "2022-01-31T22:12:04Z"
      },
      "metadata": {
        "labels": {

        },
        "annotations": {

        }
      },
      "relationships": {
        "service_instance": {
          "data": {
            "guid": "fa0e32b3-e58b-4533-8d61-59ac38b1fa51"
          }
        },
        "app": {
          "data": {
            "guid": "114edd6d-1960-46df-a1dc-0309ce8ed63b"
          }
        }
      },
      "links": {
        "self": {
          "href": "https://api.atom-kitten.capi.land/v3/service_credential_bindings/78a190a3-e3dd-4d42-8158-89aabfbd1673"
        },
        "details": {
          "href": "https://api.atom-kitten.capi.land/v3/service_credential_bindings/78a190a3-e3dd-4d42-8158-89aabfbd1673/details"
        },
        "service_instance": {
          "href": "https://api.atom-kitten.capi.land/v3/service_instances/fa0e32b3-e58b-4533-8d61-59ac38b1fa51"
        },
        "app": {
          "href": "https://api.atom-kitten.capi.land/v3/apps/114edd6d-1960-46df-a1dc-0309ce8ed63b"
        }
      }
    },
    {
      "guid": "9c4cb7fc-eb61-49d8-9c16-a949eae55ed9",
      "created_at": "2022-01-31T22:12:07Z",
      "updated_at": "2022-01-31T22:12:07Z",
      "name": null,
      "type": "app",
      "last_operation": {
        "state": "succeeded",
        "description": null,
        "type": "create",
        "updated_at": "2022-01-31T22:12:07Z",
        "created_at": "2022-01-31T22:12:07Z"
      },
      "metadata": {
        "labels": {

        },
        "annotations": {

        }
      },
      "relationships": {
        "service_instance": {
          "data": {
            "guid": "fa0e32b3-e58b-4533-8d61-59ac38b1fa51"
          }
        },
        "app": {
          "data": {
            "guid": "fa1069fb-922a-4a19-8a31-9129a82baff1"
          }
        }
      },
      "links": {
        "self": {
          "href": "https://api.atom-kitten.capi.land/v3/service_credential_bindings/9c4cb7fc-eb61-49d8-9c16-a949eae55ed9"
        },
        "details": {
          "href": "https://api.atom-kitten.capi.land/v3/service_credential_bindings/9c4cb7fc-eb61-49d8-9c16-a949eae55ed9/details"
        },
        "service_instance": {
          "href": "https://api.atom-kitten.capi.land/v3/service_instances/fa0e32b3-e58b-4533-8d61-59ac38b1fa51"
        },
        "app": {
          "href": "https://api.atom-kitten.capi.land/v3/apps/fa1069fb-922a-4a19-8a31-9129a82baff1"
        }
      }
    }
  ]
}
```

---

### Dev Notes

* Remember to handle authentication as part of this story
* API docs: https://v3-apidocs.cloudfoundry.org/version/3.113.0/index.html#list-service-credential-bindings

**Comment by tcdowney** [comment]
For reference, here are three `CFServiceInstance` YAMLs that cover these A/Cs.

Binding from App A to Service A
Binding from App A to Service B
Binding from App B to Service B

```
---
apiVersion: services.cloudfoundry.org/v1alpha1
kind: CFServiceBinding
metadata:
  name: cb90b250-68b8-499b-9667-99cc47419c9b
  namespace: 458d35bd-4c9b-4fd2-bf2d-f0deb162a33b
  labels:
    servicebinding.io/provisioned-service: "true"
    workloads.cloudfoundry.org/app-guid: "70fd71af-a2bb-4aea-b060-86f2c51f6588"
spec:
  name: dora-binding-service-one
  service:
    apiVersion: services.cloudfoundry.org/v1alpha1
    kind: CFServiceInstance
    name: 7219f578-bbf9-47ba-97c0-09cdecd2713a
  secretName: 7219f578-bbf9-47ba-97c0-09cdecd2713a
  appRef:
    name: 70fd71af-a2bb-4aea-b060-86f2c51f6588


---
apiVersion: services.cloudfoundry.org/v1alpha1
kind: CFServiceBinding
metadata:
  name: a438ffa5-c779-49d2-8158-2f43b771a0f4
  namespace: 458d35bd-4c9b-4fd2-bf2d-f0deb162a33b
  labels:
    servicebinding.io/provisioned-service: "true"
    workloads.cloudfoundry.org/app-guid: "70fd71af-a2bb-4aea-b060-86f2c51f6588"
spec:
  name: dora-binding-service-two
  service:
    apiVersion: services.cloudfoundry.org/v1alpha1
    kind: CFServiceInstance
    name: 9d56fbb7-7011-4c78-a27f-027e07423f56
  secretName: 9d56fbb7-7011-4c78-a27f-027e07423f56
  appRef:
    name: 70fd71af-a2bb-4aea-b060-86f2c51f6588

---
apiVersion: services.cloudfoundry.org/v1alpha1
kind: CFServiceBinding
metadata:
  name: 4dea6adb-47ad-449b-83b3-c2ddc79afcf4
  namespace: 458d35bd-4c9b-4fd2-bf2d-f0deb162a33b
  labels:
    servicebinding.io/provisioned-service: "true"
    workloads.cloudfoundry.org/app-guid: "996c85f3-996c-4b88-9c7d-1b9ed9729ce7"
spec:
  name: node-binding-service-two
  service:
    apiVersion: services.cloudfoundry.org/v1alpha1
    kind: CFServiceInstance
    name: 9d56fbb7-7011-4c78-a27f-027e07423f56
  secretName: 9d56fbb7-7011-4c78-a27f-027e07423f56
  appRef:
    name: 996c85f3-996c-4b88-9c7d-1b9ed9729ce7
```
